#!/usr/bin/tclsh

puts ""

set syslogs "RP/0/RP0/CPU0:rmonc401cts#show run service cgn cgse1
service cgn cgse1
 service-location preferred-active 0/6/CPU0
 service-type tunnel v6rd v6RD1
  tos 0
  path-mtu 1472
  br
   ipv6-prefix 2602:300::/28
   source-address 12.83.49.81
   unicast address 2602:300:c533:1510::27
  !
  address-family ipv4
   interface ServiceApp41
  !
  address-family ipv6
   interface ServiceApp61
  !
 !
!
"

set ports ""
set ipv4 0
set ipv6 0
set IPv4_ServiceApp ""
set IPv6_ServiceApp ""

foreach line [split $syslogs "\n"] {
  regsub -all {[ \r\t\n]+} $line " " line
  regsub -all {^[ ]} $line "" line
  regsub -all {[ ]$} $line "" line

  if {[regexp {^service-location .* 0\/\d+\/CPU0$} $line]} {
    regexp {^service-location .* 0\/(\d+)\/CPU0$} $line - slot
  }

  if {[regexp {^address-family ipv4$} $line]} {
    set ipv4 1
  }
  if {[regexp {^address-family ipv6$} $line]} {
    set ipv6 1 
  }

  if {[regexp {^interface ServiceApp} $line]} {
    if {$ipv4 == 1} {
      regexp {^interface (ServiceApp\d+)$} $line - IPv4_ServiceApp
      set ipv4 0
      set ipv6 0
    }

    if {$ipv6 == 1} {
      regexp {^interface (ServiceApp\d+)$} $line - IPv6_ServiceApp
      set ipv4 0
      set ipv6 0
    }
  }
}

puts "slot: $slot"
puts "IPv4_ServiceApp: $IPv4_ServiceApp"
puts "IPv6_ServiceApp: $IPv6_ServiceApp"

puts ""
