---
- hosts: PE73
  gather_facts: false
  connection: local

  tasks:
  - name: telnet,login and execute command
    ignore_errors: true
    expect:
      command: telnet "{{ ansible_host }}"
      responses:
        (?i)username: "abc"
        (?i)password: "abc"
        (?i)#: "admin show platform\r\nexit"
#        (?i)#: "\r\nlogout\r\nexit\r\nquit"
      echo: yes
    register: telnet_output


  - name: Debug output
    debug: var=telnet_output.stdout_lines
